sw_platform_home:
    path:     /
    defaults: { 
        _controller: SWPlatformBundle:Platform:index }

sw_platform_contact:
    path:     /contact 
    defaults: {
        _controller: SWPlatformBundle:Platform:contact }

sw_platform_news:
    path:     /news/{page}
    defaults: { 
        _controller: SWPlatformBundle:News:news, page: 1  } 
    requirements:
        page: \d*      

sw_platform_news_info:
    path:     /news-info/{id}
    defaults: { 
        _controller: SWPlatformBundle:News:view }   
    requirements:
        id: \d+

sw_platform_biography:
    path:     /biography 
    defaults: {
        _controller: SWPlatformBundle:Platform:biography }

sw_platform_discography:
    path:     /discography/{id}
    defaults: {
        _controller: SWPlatformBundle:Discography:discography }
    requirements:
        id: \d+

sw_platform_discography_info:
    path:     /discography-info/{id}
    defaults: {
        _controller: SWPlatformBundle:Discography:view }
    requirements:
        id: \d+