<?php

namespace SW\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscRepository extends \Doctrine\ORM\EntityRepository
{
	public function myDisc($id) {
   		$query = $this->_em->createQuery('
			SELECT d FROM SWPlatformBundle:Disc d
			WHERE d.typedisc = :id
			ORDER BY d.id DESC ')
   		-> setParameter('id', $id);

   		return ($query->getResult());
	}
}
