<?php

namespace SW\PlatformBundle\Repository;

/**
 * DiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscRepository extends \Doctrine\ORM\EntityRepository
{
}
