<?php

namespace SW\PlatformBundle\Repository;

/**
 * HeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
