<?php

namespace SW\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function myNews($page, $nbPerPage) {
   		$query = $this->_em->createQuery('
			SELECT n FROM SWPlatformBundle:News n
			ORDER BY n.id DESC');

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}
}
