<?php

namespace SW\PlatformBundle\Repository;

/**
 * SongDiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongDiscRepository extends \Doctrine\ORM\EntityRepository
{
}
