<?php

namespace SW\PlatformBundle\Repository;

/**
 * TypeDiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDiscRepository extends \Doctrine\ORM\EntityRepository
{
}
