<?php

namespace SW\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
	public function myVideosIndex($nbVideosPerPage) {
   		$query = $this->_em->createQuery('
			SELECT v FROM SWPlatformBundle:Video v
			ORDER BY v.id DESC ');

   		$query
		->setMaxResults($nbVideosPerPage);

   		return ($query->getResult());
	}
}
