<?php

namespace SW\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository {  
    public function myComments($idBlog, $page, $nbPerPage) {
        $query = $this->_em->createQuery('
        SELECT n FROM SWBlogBundle:Comment n
        WHERE n.blog = :idBlog
        ORDER BY n.id DESC')
        -> setParameter('idBlog', $idBlog);

    $query
    ->setFirstResult(($page-1) * $nbPerPage)
    ->setMaxResults($nbPerPage);

    return new Paginator($query, true);
    }
}
