<?php

namespace SW\EcommerceBundle\Repository;

/**
 * BasketElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketElementRepository extends \Doctrine\ORM\EntityRepository
{
}
