<?php

namespace SW\EcommerceBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByUser($user) {
        $em = $this->getEntityManager();
	
        $customer = $em->getRepository('SWEcommerceBundle:Customer')->findOneByUser($user);
        $basket = $em->getRepository('SWEcommerceBundle:Basket')->findOneByCustomer($customer);
        
        return $basket;
	}
}
