<?php

namespace SW\EcommerceBundle\Repository;

/**
 * OrderElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElementRepository extends \Doctrine\ORM\EntityRepository
{
}
