sw_blog_home:
    path:     /blog/{page}
    defaults: { 
      _controller: SWBlogBundle:Blog:index, page: 1  }
    requirements:
      year: \d+
      month: \d+
      page: \d*   

sw_blog_archive:
    path:     /blog/{year}-{month}/{page}
    defaults: { 
      _controller: SWBlogBundle:Blog:index, page: 1  }
    requirements:
      year: \d+
      month: \d+
      page: \d*   

sw_blog_show:
    path:  /blog-info/{id}/{page}
    defaults: { 
      _controller: SWBlogBundle:Blog:show, page: 1  }
    requirements:
        id: \d+
        page: \d*   

sw_blog_research:
    path:     /blog/research/{search}/{page}
    defaults: { 
      _controller: SWBlogBundle:Blog:index, page: 1  }
    requirements:
      search: \w*
      page: \d*